# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

# Define the number of master and worker nodes
# If this number is changed, remember to update setup-hosts.sh script with the new hosts IP details in /etc/hosts of each VM.
NUM_MASTER_NODE = 1
NUM_WORKER_NODE = 3

IP_NW = "192.168.5."
MASTER_IP_START = 10
NODE_IP_START = 20
LB_IP_START = 30

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false

  # Provision master node
  config.vm.define "single-master" do |node|
    # Name shown in the GUI
    node.vm.provider "virtualbox" do |vb|
      vb.name = "single-master"
      vb.memory = 2048
      vb.cpus = 2
    end
    node.vm.hostname = "single-master"
    node.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START + 1}"
    node.vm.network "forwarded_port", guest: 22, host: "#{2710 + 1}"
    node.vm.provision "setup-hosts", :type => "shell", :path => "../scripts/setup-hosts.sh" do |s|
      s.args = ["enp0s8"]
    end
    node.vm.provision "setup-dns", type: "shell", :path => "../scripts/update-dns.sh"
    node.vm.provision "file", source: "../scripts/cert_verify.sh", destination: "$HOME/"
  end

  # Provision worker nodes
  (1..NUM_WORKER_NODE).each do |i|
    config.vm.define "single-worker-#{i}" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "single-worker-#{i}"
            vb.memory = 1024
            vb.cpus = 1
        end
        node.vm.hostname = "single-worker-#{i}"
        node.vm.network :private_network, ip: IP_NW + "#{NODE_IP_START + i}"
	      node.vm.network "forwarded_port", guest: 22, host: "#{2720 + i}"
        node.vm.provision "setup-hosts", :type => "shell", :path => "../scripts/setup-hosts.sh" do |s|
          s.args = ["enp0s8"]
        end
        node.vm.provision "setup-dns", type: "shell", :path => "../scripts/update-dns.sh"
        node.vm.provision "install-docker", type: "shell", :path => "../scripts/install-docker-2.sh"
        node.vm.provision "allow-bridge-nf-traffic", :type => "shell", :path => "../scripts/allow-bridge-nf-traffic.sh"
        node.vm.provision "file", source: "../scripts/cert_verify.sh", destination: "$HOME/"
    end
  end
end
